[package]
name = "nicholasforeman/moonlite"
description = "A light-weight, runtime player for sequences created in Moon Animator 2."
version = "0.9.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]